# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from erc_dex.models.account import Account  # noqa: F401,E501
from erc_dex.models.user import User  # noqa: F401,E501


class AuthorizedWallet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'date_created': 'datetime',
        'date_updated': 'datetime',
        'address': 'str',
        'account_id': 'float',
        'user_id': 'float',
        'account': 'Account',
        'user': 'User'
    }

    attribute_map = {
        'id': 'id',
        'date_created': 'dateCreated',
        'date_updated': 'dateUpdated',
        'address': 'address',
        'account_id': 'accountId',
        'user_id': 'userId',
        'account': 'account',
        'user': 'user'
    }

    def __init__(self, id=None, date_created=None, date_updated=None, address=None, account_id=None, user_id=None, account=None, user=None):  # noqa: E501
        """AuthorizedWallet - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._date_created = None
        self._date_updated = None
        self._address = None
        self._account_id = None
        self._user_id = None
        self._account = None
        self._user = None
        self.discriminator = None

        self.id = id
        self.date_created = date_created
        self.date_updated = date_updated
        self.address = address
        self.account_id = account_id
        self.user_id = user_id
        self.account = account
        self.user = user

    @property
    def id(self):
        """Gets the id of this AuthorizedWallet.  # noqa: E501

        Unique Identifier  # noqa: E501

        :return: The id of this AuthorizedWallet.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AuthorizedWallet.

        Unique Identifier  # noqa: E501

        :param id: The id of this AuthorizedWallet.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def date_created(self):
        """Gets the date_created of this AuthorizedWallet.  # noqa: E501

        Date of creation  # noqa: E501

        :return: The date_created of this AuthorizedWallet.  # noqa: E501
        :rtype: datetime
        """
        return self._date_created

    @date_created.setter
    def date_created(self, date_created):
        """Sets the date_created of this AuthorizedWallet.

        Date of creation  # noqa: E501

        :param date_created: The date_created of this AuthorizedWallet.  # noqa: E501
        :type: datetime
        """
        if date_created is None:
            raise ValueError("Invalid value for `date_created`, must not be `None`")  # noqa: E501

        self._date_created = date_created

    @property
    def date_updated(self):
        """Gets the date_updated of this AuthorizedWallet.  # noqa: E501

        Date of updated  # noqa: E501

        :return: The date_updated of this AuthorizedWallet.  # noqa: E501
        :rtype: datetime
        """
        return self._date_updated

    @date_updated.setter
    def date_updated(self, date_updated):
        """Sets the date_updated of this AuthorizedWallet.

        Date of updated  # noqa: E501

        :param date_updated: The date_updated of this AuthorizedWallet.  # noqa: E501
        :type: datetime
        """
        if date_updated is None:
            raise ValueError("Invalid value for `date_updated`, must not be `None`")  # noqa: E501

        self._date_updated = date_updated

    @property
    def address(self):
        """Gets the address of this AuthorizedWallet.  # noqa: E501

        Ethereum Account Address  # noqa: E501

        :return: The address of this AuthorizedWallet.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AuthorizedWallet.

        Ethereum Account Address  # noqa: E501

        :param address: The address of this AuthorizedWallet.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def account_id(self):
        """Gets the account_id of this AuthorizedWallet.  # noqa: E501


        :return: The account_id of this AuthorizedWallet.  # noqa: E501
        :rtype: float
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this AuthorizedWallet.


        :param account_id: The account_id of this AuthorizedWallet.  # noqa: E501
        :type: float
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def user_id(self):
        """Gets the user_id of this AuthorizedWallet.  # noqa: E501


        :return: The user_id of this AuthorizedWallet.  # noqa: E501
        :rtype: float
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AuthorizedWallet.


        :param user_id: The user_id of this AuthorizedWallet.  # noqa: E501
        :type: float
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def account(self):
        """Gets the account of this AuthorizedWallet.  # noqa: E501


        :return: The account of this AuthorizedWallet.  # noqa: E501
        :rtype: Account
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this AuthorizedWallet.


        :param account: The account of this AuthorizedWallet.  # noqa: E501
        :type: Account
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def user(self):
        """Gets the user of this AuthorizedWallet.  # noqa: E501


        :return: The user of this AuthorizedWallet.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AuthorizedWallet.


        :param user: The user of this AuthorizedWallet.  # noqa: E501
        :type: User
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorizedWallet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
