# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from erc_dex.models.i_cancel_order_data import ICancelOrderData  # noqa: F401,E501


class ICancelOrdersRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cancellations': 'list[ICancelOrderData]'
    }

    attribute_map = {
        'cancellations': 'cancellations'
    }

    def __init__(self, cancellations=None):  # noqa: E501
        """ICancelOrdersRequest - a model defined in Swagger"""  # noqa: E501

        self._cancellations = None
        self.discriminator = None

        self.cancellations = cancellations

    @property
    def cancellations(self):
        """Gets the cancellations of this ICancelOrdersRequest.  # noqa: E501


        :return: The cancellations of this ICancelOrdersRequest.  # noqa: E501
        :rtype: list[ICancelOrderData]
        """
        return self._cancellations

    @cancellations.setter
    def cancellations(self, cancellations):
        """Sets the cancellations of this ICancelOrdersRequest.


        :param cancellations: The cancellations of this ICancelOrdersRequest.  # noqa: E501
        :type: list[ICancelOrderData]
        """
        if cancellations is None:
            raise ValueError("Invalid value for `cancellations`, must not be `None`")  # noqa: E501

        self._cancellations = cancellations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ICancelOrdersRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
