# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IFillRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote_id': 'float',
        'signature': 'str'
    }

    attribute_map = {
        'quote_id': 'quoteId',
        'signature': 'signature'
    }

    def __init__(self, quote_id=None, signature=None):  # noqa: E501
        """IFillRequest - a model defined in Swagger"""  # noqa: E501

        self._quote_id = None
        self._signature = None
        self.discriminator = None

        self.quote_id = quote_id
        self.signature = signature

    @property
    def quote_id(self):
        """Gets the quote_id of this IFillRequest.  # noqa: E501

        ID of a provided quote  # noqa: E501

        :return: The quote_id of this IFillRequest.  # noqa: E501
        :rtype: float
        """
        return self._quote_id

    @quote_id.setter
    def quote_id(self, quote_id):
        """Sets the quote_id of this IFillRequest.

        ID of a provided quote  # noqa: E501

        :param quote_id: The quote_id of this IFillRequest.  # noqa: E501
        :type: float
        """
        if quote_id is None:
            raise ValueError("Invalid value for `quote_id`, must not be `None`")  # noqa: E501

        self._quote_id = quote_id

    @property
    def signature(self):
        """Gets the signature of this IFillRequest.  # noqa: E501

        Signed transaction hash  # noqa: E501

        :return: The signature of this IFillRequest.  # noqa: E501
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this IFillRequest.

        Signed transaction hash  # noqa: E501

        :param signature: The signature of this IFillRequest.  # noqa: E501
        :type: str
        """
        if signature is None:
            raise ValueError("Invalid value for `signature`, must not be `None`")  # noqa: E501

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IFillRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
