# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IMaintenanceStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_maintenance': 'bool',
        'reason': 'str'
    }

    attribute_map = {
        'is_maintenance': 'isMaintenance',
        'reason': 'reason'
    }

    def __init__(self, is_maintenance=None, reason=None):  # noqa: E501
        """IMaintenanceStatus - a model defined in Swagger"""  # noqa: E501

        self._is_maintenance = None
        self._reason = None
        self.discriminator = None

        self.is_maintenance = is_maintenance
        if reason is not None:
            self.reason = reason

    @property
    def is_maintenance(self):
        """Gets the is_maintenance of this IMaintenanceStatus.  # noqa: E501


        :return: The is_maintenance of this IMaintenanceStatus.  # noqa: E501
        :rtype: bool
        """
        return self._is_maintenance

    @is_maintenance.setter
    def is_maintenance(self, is_maintenance):
        """Sets the is_maintenance of this IMaintenanceStatus.


        :param is_maintenance: The is_maintenance of this IMaintenanceStatus.  # noqa: E501
        :type: bool
        """
        if is_maintenance is None:
            raise ValueError("Invalid value for `is_maintenance`, must not be `None`")  # noqa: E501

        self._is_maintenance = is_maintenance

    @property
    def reason(self):
        """Gets the reason of this IMaintenanceStatus.  # noqa: E501


        :return: The reason of this IMaintenanceStatus.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this IMaintenanceStatus.


        :param reason: The reason of this IMaintenanceStatus.  # noqa: E501
        :type: str
        """

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IMaintenanceStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
