# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from erc_dex.models.order import Order  # noqa: F401,E501


class IOrderData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order': 'Order',
        'remaining_fillable_amount': 'str'
    }

    attribute_map = {
        'order': 'order',
        'remaining_fillable_amount': 'remainingFillableAmount'
    }

    def __init__(self, order=None, remaining_fillable_amount=None):  # noqa: E501
        """IOrderData - a model defined in Swagger"""  # noqa: E501

        self._order = None
        self._remaining_fillable_amount = None
        self.discriminator = None

        self.order = order
        self.remaining_fillable_amount = remaining_fillable_amount

    @property
    def order(self):
        """Gets the order of this IOrderData.  # noqa: E501


        :return: The order of this IOrderData.  # noqa: E501
        :rtype: Order
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this IOrderData.


        :param order: The order of this IOrderData.  # noqa: E501
        :type: Order
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order

    @property
    def remaining_fillable_amount(self):
        """Gets the remaining_fillable_amount of this IOrderData.  # noqa: E501


        :return: The remaining_fillable_amount of this IOrderData.  # noqa: E501
        :rtype: str
        """
        return self._remaining_fillable_amount

    @remaining_fillable_amount.setter
    def remaining_fillable_amount(self, remaining_fillable_amount):
        """Sets the remaining_fillable_amount of this IOrderData.


        :param remaining_fillable_amount: The remaining_fillable_amount of this IOrderData.  # noqa: E501
        :type: str
        """
        if remaining_fillable_amount is None:
            raise ValueError("Invalid value for `remaining_fillable_amount`, must not be `None`")  # noqa: E501

        self._remaining_fillable_amount = remaining_fillable_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IOrderData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
