# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from erc_dex.models.i_price_level import IPriceLevel  # noqa: F401,E501


class IOrderBookListing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price_levels': 'list[IPriceLevel]'
    }

    attribute_map = {
        'price_levels': 'priceLevels'
    }

    def __init__(self, price_levels=None):  # noqa: E501
        """IOrderBookListing - a model defined in Swagger"""  # noqa: E501

        self._price_levels = None
        self.discriminator = None

        self.price_levels = price_levels

    @property
    def price_levels(self):
        """Gets the price_levels of this IOrderBookListing.  # noqa: E501


        :return: The price_levels of this IOrderBookListing.  # noqa: E501
        :rtype: list[IPriceLevel]
        """
        return self._price_levels

    @price_levels.setter
    def price_levels(self, price_levels):
        """Sets the price_levels of this IOrderBookListing.


        :param price_levels: The price_levels of this IOrderBookListing.  # noqa: E501
        :type: list[IPriceLevel]
        """
        if price_levels is None:
            raise ValueError("Invalid value for `price_levels`, must not be `None`")  # noqa: E501

        self._price_levels = price_levels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IOrderBookListing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
