# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IPriceLevel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price': 'str',
        'volume': 'str',
        'volume_ratio': 'float'
    }

    attribute_map = {
        'price': 'price',
        'volume': 'volume',
        'volume_ratio': 'volumeRatio'
    }

    def __init__(self, price=None, volume=None, volume_ratio=None):  # noqa: E501
        """IPriceLevel - a model defined in Swagger"""  # noqa: E501

        self._price = None
        self._volume = None
        self._volume_ratio = None
        self.discriminator = None

        self.price = price
        self.volume = volume
        self.volume_ratio = volume_ratio

    @property
    def price(self):
        """Gets the price of this IPriceLevel.  # noqa: E501


        :return: The price of this IPriceLevel.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this IPriceLevel.


        :param price: The price of this IPriceLevel.  # noqa: E501
        :type: str
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def volume(self):
        """Gets the volume of this IPriceLevel.  # noqa: E501


        :return: The volume of this IPriceLevel.  # noqa: E501
        :rtype: str
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this IPriceLevel.


        :param volume: The volume of this IPriceLevel.  # noqa: E501
        :type: str
        """
        if volume is None:
            raise ValueError("Invalid value for `volume`, must not be `None`")  # noqa: E501

        self._volume = volume

    @property
    def volume_ratio(self):
        """Gets the volume_ratio of this IPriceLevel.  # noqa: E501


        :return: The volume_ratio of this IPriceLevel.  # noqa: E501
        :rtype: float
        """
        return self._volume_ratio

    @volume_ratio.setter
    def volume_ratio(self, volume_ratio):
        """Sets the volume_ratio of this IPriceLevel.


        :param volume_ratio: The volume_ratio of this IPriceLevel.  # noqa: E501
        :type: float
        """
        if volume_ratio is None:
            raise ValueError("Invalid value for `volume_ratio`, must not be `None`")  # noqa: E501

        self._volume_ratio = volume_ratio

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPriceLevel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
