# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from erc_dex.models.i_order_fill import IOrderFill  # noqa: F401,E501


class IRequestFillRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'taker': 'str',
        'fills': 'list[IOrderFill]'
    }

    attribute_map = {
        'taker': 'taker',
        'fills': 'fills'
    }

    def __init__(self, taker=None, fills=None):  # noqa: E501
        """IRequestFillRequest - a model defined in Swagger"""  # noqa: E501

        self._taker = None
        self._fills = None
        self.discriminator = None

        self.taker = taker
        self.fills = fills

    @property
    def taker(self):
        """Gets the taker of this IRequestFillRequest.  # noqa: E501

        Account requesting the trade  # noqa: E501

        :return: The taker of this IRequestFillRequest.  # noqa: E501
        :rtype: str
        """
        return self._taker

    @taker.setter
    def taker(self, taker):
        """Sets the taker of this IRequestFillRequest.

        Account requesting the trade  # noqa: E501

        :param taker: The taker of this IRequestFillRequest.  # noqa: E501
        :type: str
        """
        if taker is None:
            raise ValueError("Invalid value for `taker`, must not be `None`")  # noqa: E501

        self._taker = taker

    @property
    def fills(self):
        """Gets the fills of this IRequestFillRequest.  # noqa: E501

        Collection of trade requests  # noqa: E501

        :return: The fills of this IRequestFillRequest.  # noqa: E501
        :rtype: list[IOrderFill]
        """
        return self._fills

    @fills.setter
    def fills(self, fills):
        """Sets the fills of this IRequestFillRequest.

        Collection of trade requests  # noqa: E501

        :param fills: The fills of this IRequestFillRequest.  # noqa: E501
        :type: list[IOrderFill]
        """
        if fills is None:
            raise ValueError("Invalid value for `fills`, must not be `None`")  # noqa: E501

        self._fills = fills

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IRequestFillRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
