# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from erc_dex.api_client import ApiClient


class AggregatedOrdersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_aggregated_orders(self, base_symbol, quote_symbol, **kwargs):  # noqa: E501
        """get_aggregated_orders  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_aggregated_orders(base_symbol, quote_symbol, async=True)
        >>> result = thread.get()

        :param async bool
        :param str base_symbol: (required)
        :param str quote_symbol: (required)
        :return: IAggregatedOrderData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_aggregated_orders_with_http_info(base_symbol, quote_symbol, **kwargs)  # noqa: E501
        else:
            (data) = self.get_aggregated_orders_with_http_info(base_symbol, quote_symbol, **kwargs)  # noqa: E501
            return data

    def get_aggregated_orders_with_http_info(self, base_symbol, quote_symbol, **kwargs):  # noqa: E501
        """get_aggregated_orders  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_aggregated_orders_with_http_info(base_symbol, quote_symbol, async=True)
        >>> result = thread.get()

        :param async bool
        :param str base_symbol: (required)
        :param str quote_symbol: (required)
        :return: IAggregatedOrderData
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['base_symbol', 'quote_symbol']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_aggregated_orders" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'base_symbol' is set
        if ('base_symbol' not in params or
                params['base_symbol'] is None):
            raise ValueError("Missing the required parameter `base_symbol` when calling `get_aggregated_orders`")  # noqa: E501
        # verify the required parameter 'quote_symbol' is set
        if ('quote_symbol' not in params or
                params['quote_symbol'] is None):
            raise ValueError("Missing the required parameter `quote_symbol` when calling `get_aggregated_orders`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'base_symbol' in params:
            query_params.append(('baseSymbol', params['base_symbol']))  # noqa: E501
        if 'quote_symbol' in params:
            query_params.append(('quoteSymbol', params['quote_symbol']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/aggregated_orders', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='IAggregatedOrderData',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
