# coding: utf-8

"""
    ERC dEX Aqueduct REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.api.orders_api import OrdersApi  # noqa: E501
from erc_dex.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex.api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_orders(self):
        """Test case for cancel_orders

        """
        pass

    def test_create_order(self):
        """Test case for create_order

        """
        pass

    def test_get_order_by_hash(self):
        """Test case for get_order_by_hash

        """
        pass

    def test_get_order_config(self):
        """Test case for get_order_config

        """
        pass

    def test_get_orderbook(self):
        """Test case for get_orderbook

        """
        pass

    def test_get_orders(self):
        """Test case for get_orders

        """
        pass


if __name__ == '__main__':
    unittest.main()
