# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.api.news_api import NewsApi  # noqa: E501
from erc_dex.rest import ApiException


class TestNewsApi(unittest.TestCase):
    """NewsApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex.api.news_api.NewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_crypto_panic_news(self):
        """Test case for get_crypto_panic_news

        """
        pass

    def test_get_erc_dex_news(self):
        """Test case for get_erc_dex_news

        """
        pass


if __name__ == '__main__':
    unittest.main()
