# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.api.trading_view_api import TradingViewApi  # noqa: E501
from erc_dex.rest import ApiException


class TestTradingViewApi(unittest.TestCase):
    """TradingViewApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex.api.trading_view_api.TradingViewApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_trading_view_logs(self):
        """Test case for get_trading_view_logs

        """
        pass


if __name__ == '__main__':
    unittest.main()
