# coding: utf-8

"""
    ERC dEX Aqueduct REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.api.networks_api import NetworksApi  # noqa: E501
from erc_dex.rest import ApiException


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex.api.networks_api.NetworksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_supported_network(self):
        """Test case for get_supported_network

        """
        pass

    def test_is_maintenance(self):
        """Test case for is_maintenance

        """
        pass


if __name__ == '__main__':
    unittest.main()
