# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.models.i_get_market_order_quote_by_percentage_request import IGetMarketOrderQuoteByPercentageRequest  # noqa: E501
from erc_dex.rest import ApiException


class TestIGetMarketOrderQuoteByPercentageRequest(unittest.TestCase):
    """IGetMarketOrderQuoteByPercentageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIGetMarketOrderQuoteByPercentageRequest(self):
        """Test IGetMarketOrderQuoteByPercentageRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex.models.i_get_market_order_quote_by_percentage_request.IGetMarketOrderQuoteByPercentageRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
