# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.models.i_get_news_items_response import IGetNewsItemsResponse  # noqa: E501
from erc_dex.rest import ApiException


class TestIGetNewsItemsResponse(unittest.TestCase):
    """IGetNewsItemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIGetNewsItemsResponse(self):
        """Test IGetNewsItemsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex.models.i_get_news_items_response.IGetNewsItemsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
