# coding: utf-8

"""
    ERC dEX Aqueduct REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.models.i_orderbook_side import IOrderbookSide  # noqa: E501
from erc_dex.rest import ApiException


class TestIOrderbookSide(unittest.TestCase):
    """IOrderbookSide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIOrderbookSide(self):
        """Test IOrderbookSide"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex.models.i_orderbook_side.IOrderbookSide()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
