# coding: utf-8

"""
    ERC dEX Aqueduct REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.models.rebate_contract import RebateContract  # noqa: E501
from erc_dex.rest import ApiException


class TestRebateContract(unittest.TestCase):
    """RebateContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRebateContract(self):
        """Test RebateContract"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex.models.rebate_contract.RebateContract()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
