# coding: utf-8

"""
    ERC dEX Aqueduct REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.api.trade_api import TradeApi  # noqa: E501
from erc_dex.rest import ApiException


class TestTradeApi(unittest.TestCase):
    """TradeApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex.api.trade_api.TradeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fill(self):
        """Test case for fill

        """
        pass

    def test_get_market_quote(self):
        """Test case for get_market_quote

        """
        pass

    def test_get_market_quote_by_percent(self):
        """Test case for get_market_quote_by_percent

        """
        pass

    def test_get_receipt(self):
        """Test case for get_receipt

        """
        pass

    def test_get_receipts(self):
        """Test case for get_receipts

        """
        pass

    def test_request_fill(self):
        """Test case for request_fill

        """
        pass


if __name__ == '__main__':
    unittest.main()
