# coding: utf-8

"""
    ERC dEX REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex
from erc_dex.models.i_network import INetwork  # noqa: E501
from erc_dex.rest import ApiException


class TestINetwork(unittest.TestCase):
    """INetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testINetwork(self):
        """Test INetwork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex.models.i_network.INetwork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
