# coding: utf-8

"""
    ERC dEX Proxy Service

    Command line app for ERC dEX Trading Automation  # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex_proxy
from erc_dex_proxy.models.i_create_order_args import ICreateOrderArgs  # noqa: E501
from erc_dex_proxy.rest import ApiException


class TestICreateOrderArgs(unittest.TestCase):
    """ICreateOrderArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testICreateOrderArgs(self):
        """Test ICreateOrderArgs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex_proxy.models.i_create_order_args.ICreateOrderArgs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
