# coding: utf-8

"""
    ERC dEX Proxy Service

    Command line app for ERC dEX Trading Automation  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex_proxy
from erc_dex_proxy.api.allowance_api import AllowanceApi  # noqa: E501
from erc_dex_proxy.rest import ApiException


class TestAllowanceApi(unittest.TestCase):
    """AllowanceApi unit test stubs"""

    def setUp(self):
        self.api = erc_dex_proxy.api.allowance_api.AllowanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_allowance(self):
        """Test case for get_allowance

        """
        pass

    def test_remove_allowance(self):
        """Test case for remove_allowance

        """
        pass

    def test_set_allowance(self):
        """Test case for set_allowance

        """
        pass

    def test_set_unlimited_allowance(self):
        """Test case for set_unlimited_allowance

        """
        pass


if __name__ == '__main__':
    unittest.main()
