# coding: utf-8

"""
    ERC dEX Proxy Service

    Command line app for ERC dEX Trading Automation  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import erc_dex_proxy
from erc_dex_proxy.models.i_fill_receipt_log import IFillReceiptLog  # noqa: E501
from erc_dex_proxy.rest import ApiException


class TestIFillReceiptLog(unittest.TestCase):
    """IFillReceiptLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIFillReceiptLog(self):
        """Test IFillReceiptLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = erc_dex_proxy.models.i_fill_receipt_log.IFillReceiptLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
